article:
  type: tech
  share: [ link ]
menubar:
  columns: 2
  items:
    - id: home
      theme: ''
      title: 首页
      icon: ''
      url: /
    - id: wiki
      theme: ''
      title: 文档
      icon: ''
      url: /wiki
comments:
  service: giscus
  giscus:
    src: https://giscus.app/client.js
    data-repo: yusheng929/pinglun
    data-repo-id: R_kgDOLVGwmg
    data-category: Announcements
    data-category-id: DIC_kwDOLVGwms4CnJGu
    data-mapping: pathname
    data-strict: 0
    data-reactions-enabled: 1
    data-emit-metadata: 0
    data-input-position: top
    data-theme: preferred_color_scheme
    data-lang: zh-CN
    data-loading: lazy
    crossorigin: anonymous